### ISSUE TITLE
Can't install 

### ISSUE THREAD

**Issue by i3ima** [fhadiel/ricemood#3]
Error log
sudo npm install -g ricemod
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/ricemod - Not found
npm ERR! 404 
npm ERR! 404  'ricemod@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-12-07T20_14_55_287Z-debug.log

**Comment by f0x48** [comment]
it's ```ricemood``` not ```ricemod```
