### ISSUE TITLE
ricemood -a doesn't use colors given from ricemood -i

### ISSUE THREAD

**Issue by fezboy** [fhadiel/ricemood#4]
So when I run `ricemood -i *image file*` it gives this output:
```
[
  [ [ "V", "Vibrant" ], [ 208, 29, 65 ] ],
  [
    [ "LV", "LightVibrant" ],
    [ 238.7746835443038, 138.6253164556962, 158.76708860759493 ]
  ],
  [ [ "DV", "DarkVibrant" ], [ 124, 4, 11 ] ],
  [ [ "M", "Muted" ], [ 93, 170, 131 ] ],
  [ [ "LM", "LightMuted" ], [ 197, 182, 175 ] ],
  [ [ "DM", "DarkMuted" ], [ 91, 59, 44 ] ]
]
```

When I paste the values for vibrant into a color picker (https://duckduckgo.com/?q=color+picker) it gives the hex code #d01d41 and displays a pinkish color.  When I run `ricemood -a` it fills `^r@V^` with #D20C0F.   Any ideas as to what's happening?

**Comment by f0x48** [comment]
I'm not able to reproduce it.
Please check your ```quality``` value at ```ricemood.ini``` make sure it's ```1```

**Comment by fezboy** [comment]
here's my ricemood.ini: https://pastebin.com/jvD56Dwe
test.conf is just ^r@V^

**Comment by f0x48** [comment]
Still can't reproduce.
Can you provide the image?

Anyway, why do you need ```-i``` function?

**Comment by fezboy** [comment]
Sorry to have bothered you but I just realized that -a was using a different image than I was running through -i.  My primary and secondary monitors use two crops from the same image, a while ago pywal set one of them to both monitors.  I fixed this with feh just recently, and it seems that ricemood decided to switch to the second one.  I thought this and changed the background back to using just the first on both, but for some reason feh is still telling ricemood to use the second.

The first (which had been on both): https://drive.google.com/open?id=1zzX70lCj_8oCAx5KI7zi0SavovmpsXcG (alastorWallpaper.png)
The second (which I put on my vertical monitor): https://drive.google.com/open?id=1RDtEXoXqQu2OaZfUTx8OgGDRsssSNbBu (alastorVert.png)

The output of `ricemood -a`: 
```
^^>>> ricemood -a           
[ricemood-info] You select feh for background manager
[ricemood-info] getting wallpaper...
[ricemood-info] getting color for alastorVert.png
[ricemood-info] Providing variable bg, fg
[ricemood-info] [CAUTION]
This app is really buggy, this step will overwrite

/home/fez/.config/i3/config
/home/fez/.config/polybar/config
/home/fez/.Xresources
/home/fez/.config/ricemood/test

Please backup those file first
Do you want to proceed? press Y to continue
n
[ricemood-parser] Alright Exitting...
```

And my .fehbg script:
```
#!/bin/sh
#feh --no-fehbg --bg-fill '/home/fez/Pictures/Wal/alastorVert.png' '/home/fez/Pictures/Wal/AlastorWallpaper.png' 
feh --no-fehbg --bg-fill '/home/fez/Pictures/Wal/AlastorWallpaper.png' 
```

Seems to have been both user error on my part and something weird with feh. Sorry to have bothered you; closing.

**Comment by f0x48** [comment]
@The-Bob actually, the feh wallpaper detection just read the ~/.fehbg file and use the first value of --bg-fill (wallpaper file) so it using the value in the commented line. 
```
#!/bin/sh
#feh --no-fehbg --bg-fill '/home/fez/Pictures/Wal/alastorVert.png' '/home/fez/Pictures/Wal/AlastorWallpaper.png' 
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
feh --no-fehbg --bg-fill '/home/fez/Pictures/Wal/AlastorWallpaper.png' 
```

Well, thanks for trying the program :+1:
